version: '3.8'

services:
  balloon-hud:
    build: .
    ports:
      - "8050:8050"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./static:/app/static
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env
    restart: unless-stopped
    stdin_open: true
    tty: true